name: airped
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  get_it: ^7.7.0
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.8
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  

flutter:
  uses-material-design: true
  assets:
  - assets/home/about.png
  - assets/home/baby.png
  - assets/home/tot.png
  - assets/home/tqt.png
  - assets/home/pulmao.png
  - assets/home/pc.png
  - assets/title/baby.png
  - assets/title/tot.png
  - assets/title/tqt.png
  - assets/title/lung.png
  - assets/title/pc.png
  - assets/title/about.png
  - assets/logo.png
  - assets/logoSemfundo.png
  - assets/warning.png
  - assets/about/brasaouepa.png
  - assets/about/logoCipe.png
  - assets/about/logoCapes.png
 